const LOCAL_STORAGE_KEY = "credentialId";
import { quickAlert } from "@/helpers/IonicHelpers";
import { decode, encode } from "base64-arraybuffer";

async function storeSensitiveDataToWebauthN(
  sensitiveString: string
): Promise<boolean> {
  if (!navigator.credentials) {
    await quickAlert(
      "Your browser does not support Web Authentication API. Please try a different browser."
    );
    console.error("Web Authentication API not supported on this browser.");
    return false;
  }

  let userHandle = new TextEncoder().encode(sensitiveString);

  let createOptions: CredentialCreationOptions = {
    publicKey: {
      rp: { name: "Otipi.app" },
      user: {
        id: userHandle,
        name: "Otipi Client",
        displayName: "Otipi Client",
      },
      challenge: new Uint8Array(32), // In practice, should be generated by the server
      pubKeyCredParams: [{ alg: -7, type: "public-key" }],
      authenticatorSelection: {
        authenticatorAttachment: "platform",
        requireResidentKey: true,
        userVerification: "required",
      },
    },
  };

  try {
    const credential = await navigator.credentials.create(createOptions);
    if (!credential) {
      console.error("Error: WebauthN failed to store the data");
      return false;
    }
    console.log("Registration successful", credential);
    // @ts-expect-error
    const dataAsBuffer = credential.rawId;
    const base64CredentialId: string = encode(dataAsBuffer);
    localStorage.setItem(LOCAL_STORAGE_KEY, base64CredentialId);
    return true;
  } catch (err) {
    console.error("Registration failed", err);
    return false;
  }
}

async function retrieveSensitiveDataFromWebauthNAsString(): Promise<
  string | null
> {
  const credentialId = localStorage.getItem(LOCAL_STORAGE_KEY) as string;

  // Correctly decode the Base64-encoded credential ID before using it
  let decodedCredentialId: ArrayBuffer = decode(credentialId);

  let getCredentialDefaultArgs: CredentialRequestOptions = {
    publicKey: {
      challenge: new Uint8Array(32), // Should be securely generated
      allowCredentials: [{ id: decodedCredentialId, type: "public-key" }],
      userVerification: "required",
    },
  };

  try {
    const assertion = await navigator.credentials.get(getCredentialDefaultArgs);
    console.log("Authentication successful", assertion);
    //@ts-ignore
    const responseEncoded = assertion.response.userHandle;
    let userHandle = responseEncoded
      ? new TextDecoder().decode(responseEncoded)
      : null;
    console.log("Retrieved User Handle:", userHandle);
    return userHandle;
  } catch (err) {
    console.error("Authentication failed", err);
    quickAlert(
      "There was an error retrieving your credentials. Please try again. if it persists, please reset quick login under settings."
    );
  }
  return null;
}

export function resetQuickLogin(): void {
  localStorage.removeItem(LOCAL_STORAGE_KEY);
}
export function isQuickLoginEnabled(): boolean {
  return localStorage.getItem(LOCAL_STORAGE_KEY) !== null;
}
export async function retrieveEncryptedPassFromWebauthn(): Promise<
  string | null
> {
  if (localStorage.getItem(LOCAL_STORAGE_KEY) === null) {
    return null;
  }
  const dateRecieved: string | null =
    await retrieveSensitiveDataFromWebauthNAsString();
  return dateRecieved;
}

export async function storeEncryptedPassToWebauthn(
  sensitiveString: string
): Promise<boolean> {
   // Check if sensitiveString is longer than 64 bytes
   //https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialuserentity-id
   if (new TextEncoder().encode(sensitiveString).length > 64) {
    throw new Error("Sensitive string must not be longer than 64 bytes");
  }

  if (localStorage.getItem(LOCAL_STORAGE_KEY) !== null) {
    throw new Error("WebauthN already has a stored credential");
  }
  return await storeSensitiveDataToWebauthN(sensitiveString);
}
